=== Babashonok/TATJAVA01_2017_Task05_Aliaksei_Babak/src/main/resources/scheme.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.epam.com/task5/menu"
        xmlns:tns="http://www.epam.com/task5/menu">

    <element name="menu">
        <complexType>
            <all>
                <element name="snacks" type="tns:menu_category" minOccurs="0"/>
                <element name="appetizers" type="tns:menu_category" minOccurs="0"/>
                <element name="breakfasts" type="tns:menu_category" minOccurs="0"/>
                <element name="salads" type="tns:menu_category" minOccurs="0"/>
                <element name="soups" type="tns:menu_category" minOccurs="0"/>
                <element name="fish_dishes" type="tns:menu_category" minOccurs="0"/>
                <element name="meat_dishes" type="tns:menu_category" minOccurs="0"/>
                <element name="side_dishes" type="tns:menu_category" minOccurs="0"/>
                <element name="grill_dishes" type="tns:menu_category" minOccurs="0"/>
                <element name="chef_special" type="tns:menu_category" minOccurs="0"/>
                <element name="toppings" type="tns:menu_category" minOccurs="0"/>
                <element name="desserts" type="tns:menu_category" minOccurs="0"/>
            </all>
        </complexType>
    </element>

    <complexType name="menu_category">
        <sequence>
            <element name="item" type="tns:Item" minOccurs="0" maxOccurs="unbounded"/>
        </sequence>
    </complexType>

    <complexType name="Item">
        <attribute name="id" type="ID" use="required"/>
        <sequence>
            <element name="photo" type="anyURI" minOccurs="0"/>
            <element name="name" type="string"/>
            <element name="description" type="string" minOccurs="0"/>
            <element name="portion" type="string"/>
            <element name="price" type="string" minOccurs="0"/>
        </sequence>
    </complexType>

</schema>

=== Babashonok/TATJAVA01_2017_Task05_Aliaksei_Babak/menu.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<menu xmlns="http://www.epam.com/task5/menu"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.epam.com/task5/menu src/main/resources/scheme.xsd">
    <snacks>
        <item id="1">
            <photo>1.jpeg</photo>
            <name>Ассорти рыбное</name>
            <description>Слабосоленая форель, семга</description>
            <portion>100/20/15</portion>
        </item>
        <item id="2">
            <photo>2.jpeg</photo>
            <name>Тарталетки с красной икрой</name>
            <description>Тарталетки с красной икрой</description>
            <portion>60/50</portion>
        </item>
        <item id="3">
            <photo>3.jpeg</photo>
            <name>Закуска по-русски</name>
            <description>Кусочки атлантической сельди с отварным картофелем, луком, лимоном и зеленью</description>
            <portion>70/50/2/10</portion>
        </item>
        <item id="4">
            <photo>4.jpeg</photo>
            <name>Куриный рулет</name>
            <description>Куриный рулет собственного производства</description>
            <portion>100/5</portion>
        </item>
        <item id="5">
            <photo>5.jpeg</photo>
            <name>Бастурма</name>
            <description>Вяленая вырезка из говяжьего мяса</description>
            <portion>50/5</portion>
        </item>
        <item id="6">
            <photo>6.jpeg</photo>
            <name>Ассорти мясное</name>
            <description>Нарезка из буженины, бастурмы, куриного рулета собственного производства и колбасы</description>
            <portion>100/30</portion>
        </item>
        <item id="7">
            <photo>7.jpeg</photo>
            <name>Язык отварной</name>
            <description>Нарезка нежного говяжьего языка, подается с хреном</description>
            <portion>80/20/1</portion>
        </item>
        <item id="8">
            <photo>8.jpeg</photo>
            <name>Ассорти баклажаны</name>
            <description>Жаренные баклажаны с помидорами
                1. с помидорами
                2. с чесноком
                3. с орехами</description>
            <portion>100/5</portion>
        </item>
        <item id="9">
            <photo>9.jpeg</photo>
            <name>Соленья по-домашнему</name>
            <description>Маринованные овощи</description>
            <portion>150/10</portion>
        </item>
        <item id="10">
            <photo>10.jpeg</photo>
            <name>Бабушкины угощения</name>
            <description>Ассорти из маринованных грибов</description>
            <portion>120/20/10</portion>
        </item>
        <item id="11">
            <photo>11.jpeg</photo>
            <name>Сырная тарелка</name>
            <description>Сыры Чечел, дор блю, российский, мраморный</description>
            <portion>100/5</portion>
        </item>
        <item id="12">
            <photo>12.jpeg</photo>
            <name>Брынза</name>
            <description>Рассольный сыр, изготавливаемый из овечьего молока</description>
            <portion>75/5</portion>
        </item>
        <item id="13">
            <photo>13.jpeg</photo>
            <name>Зелень</name>
            <description>Кинза, лук, петрушка, укроп, базилик</description>
            <portion>30</portion>
        </item>
        <item id="14">
            <photo>14.jpeg</photo>
            <name>Ассорти овощное</name>
            <description>Свежие помидоры, болгарский перец, огурцы редис и зелень</description>
            <portion>150/10</portion>
        </item>
        <item id="15">
            <photo>15.jpeg</photo>
            <name>Овощной букет</name>
            <description>Корейская морковь, капуста, фунчоза</description>
            <portion>150/10</portion>
        </item>
        <item id="16">
            <photo>16.jpeg</photo>
            <name>Овощи по-армянски</name>
            <description>Мелко нарезанные свежие помидоры, огурцы, болгарский перец,
                укроп, базилик, кинза, лист салата, зелень</description>
            <portion>150/40</portion>
        </item>
        <item id="17">
            <photo>17.jpeg</photo>
            <name>Сеньор помидор</name>
            <description>Помидор, фаршированный сырным сырным муссом</description>
            <portion>150/1</portion>
        </item>
        <item id="18">
            <photo>18.jpeg</photo>
            <name>Фестиваль салатов</name>
            <portion>400/10</portion>
        </item>
        <item id="19">
            <photo>19.jpeg</photo>
            <name>Оливки, маслины</name>
            <portion>50</portion>
        </item>
        <item id="20">
            <photo>20.jpeg</photo>
            <name>Лимон</name>
            <portion>60</portion>
        </item>
        <item id="21">
            <photo>21.jpeg</photo>
            <name>Мацони</name>
            <portion>300</portion>
        </item>
    </snacks>>

    <appetizers>
        <item id="22">
            <photo>22.jpeg</photo>
            <name>Лобио с шампиньонами</name>
            <description>Фасоль с шампиньонами и грецким орехом</description>
            <portion>150/5</portion>
            <price>105</price>
        </item>
        <item id="23">
            <photo>23.jpeg</photo>
            <name>Жульен</name>
            <description>1. с курицей   2. с грибами </description>
            <portion>120/1</portion>
            <price>1. 145    2. 155</price>
        </item>
        <item id="24">
            <photo>24.jpeg</photo>
            <name>Ахматар мясной</name>
            <description>Колбаса, ветчина, буженина, сыр, запеченные на мангале в лаваше</description>
            <portion>1 шт.</portion>
            <price>165</price>
        </item>
        <item id="25">
            <photo>25.jpeg</photo>
            <name>Ахматар с овощами</name>
            <description>Сыр, помидоры, зелень, запеченные на мангале в лаваше</description>
            <portion>1 шт.</portion>
            <price>150</price>
        </item>
        <item id="26">
            <photo>26.jpeg</photo>
            <name>Сюрприз</name>
            <portion>1 шт.</portion>
            <price>260</price>
        </item>
        <item id="27">
            <photo>27.jpeg</photo>
            <name>Креветки</name>
            <description>1. отварные  2. жаренные</description>
            <portion>120/30</portion>
            <price>1. 135    2.155</price>
        </item>
        <item id="28">
            <photo>28.jpeg</photo>
            <name>Мидии по-туррецки</name>
            <description>Мидии, фаршированные сыром и грецким орехом</description>
            <portion>150/30</portion>
            <price>190</price>
        </item>
        <item id="29">
            <photo>29.jpeg</photo>
            <name>Эскарго</name>
            <description>Виноградные улитки, фаршированные по бургундски</description>
            <portion>12 шт.</portion>
            <price>230</price>
        </item>
    </appetizers>

    <breakfasts>
        <item id="30">
            <photo>30.jpeg</photo>
            <name>Глазунья</name>
            <description>2 яйца (на выбор: ветчина, сыр, помидоры)</description>
            <portion>150</portion>
        </item>
        <item id="31">
            <photo>31.jpeg</photo>
            <name>Омлет</name>
            <portion>100</portion>
        </item>
        <item id="32">
            <photo>32.jpeg</photo>
            <name>Блинчики с мясом</name>
            <description>Жаренные блинчики с мясом</description>
            <portion>150</portion>
        </item>
    </breakfasts>
</menu>
